name: CI/CD to EKS

on:
  push:
env:
  IMAGE_NAME: alia153/final-project-ivolve


jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:v${{ github.run_number }}


  update-deployment-file:
    name: Update deployment.yaml in another repo
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Aliabdrabo/finalProject-manifests
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          path: manifests

      - name: Update image version in deployment.yaml
        run: |
          cd manifests
          sed -i "s|image:.*|image: ${{ env.IMAGE_NAME }}:v${{ github.run_number }}|" deployment.yaml
          #cat deployment.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git config user.name "Aliabdrabo"
          git config user.email "aliabdrabu78@gmail.com"
          git add .
          git commit -m "Update image tag to v${{ github.run_number }}"
          git push
